# Generated by Django 4.0.5 on 2022-06-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_alter_category_slug_alter_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='issue_point',
            field=models.CharField(blank=True, choices=[('Kiev, str. Peremohi 12', 'Kiev, str. Peremohi 12'), ('Kharkiv, str. Klochkovskay 123', 'Kharkiv, str. Klochkovskay 123')], max_length=50),
        ),
    ]
